import type { WechatTheme, WechatThemeStyles } from "../types";

export function createAdvancedThemes(sharedStyles: WechatThemeStyles) {
const industryReport: WechatTheme = {
  id: "industry-report",
  version: 1,
  name: "行业报告",
  description: "强化结论、数据、来源和对比，适合行业观察、调研复盘与趋势分析。",
  category: "report",
  recommendedFor: ["行业报告", "数据分析", "趋势观察"],
  tokens: {
    colors: { background: "#f8fafc", text: "#172033", muted: "#64748b", accent: "#0f4c81", accentSoft: "#eaf3f8" },
    typography: { titleSize: 25, h2Size: 20, h3Size: 17, bodySize: 16, bodyLineHeight: 1.86 },
  },
  styles: {
    ...sharedStyles,
    root: "display:block;width:100%;box-sizing:border-box;padding:24px 18px;background:#f8fafc;color:#172033;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif;",
    titleWrap: "display:block;margin:0 0 24px;padding:0 0 16px;border-bottom:3px solid #0f4c81;text-align:left;",
    titleText: "display:block;color:#102a43;font-size:25px;line-height:1.42;font-weight:800;letter-spacing:0;",
    subtitle: "display:block;margin:-12px 0 24px;color:#627d98;font-size:14px;line-height:1.7;",
    h2Wrap: "display:block;margin:34px 0 16px;padding:10px 13px;border-left:5px solid #0f4c81;background:#eaf3f8;",
    h2Text: "display:block;color:#102a43;font-size:20px;line-height:1.5;font-weight:800;",
    h3Wrap: "display:block;margin:25px 0 12px;padding:0 0 7px;border-bottom:1px solid #9fb3c8;",
    h3Text: "display:block;color:#174f78;font-size:17px;line-height:1.55;font-weight:700;",
    paragraph: "display:block;margin:0 0 17px;padding:0;background:transparent;color:#243b53;font-size:16px;line-height:1.86;text-align:justify;word-break:break-word;",
    leadWrap: "display:block;margin:0 0 25px;padding:16px 18px;border-top:1px solid #9fb3c8;border-bottom:1px solid #9fb3c8;background:#ffffff;",
    leadText: "display:block;margin:0;color:#334e68;font-size:16px;line-height:1.86;",
    statWrap: "display:block;margin:24px 0;padding:22px 16px;border:1px solid #bcccdc;background:#ffffff;text-align:center;",
    statValue: "display:block;margin:0;color:#0f4c81;font-size:32px;line-height:1.25;font-weight:850;",
    statLabel: "display:block;margin:8px 0 0;color:#526d82;font-size:14px;line-height:1.65;",
    compareWrap: "display:table;width:100%;margin:22px 0;border-collapse:separate;border-spacing:6px;table-layout:fixed;",
    compareColumn: "display:table-cell;width:50%;padding:14px;border-top:3px solid #0f4c81;background:#ffffff;color:#334e68;font-size:14px;line-height:1.75;vertical-align:top;",
    quoteWrap: "display:block;margin:24px 0;padding:17px 18px;border-left:4px solid #486581;background:#ffffff;",
    strong: "color:#0f4c81;font-weight:750;",
  },
};

const interviewDialogue: WechatTheme = {
  id: "interview-dialogue",
  version: 1,
  name: "访谈对话",
  description: "突出提问、回答与金句，适合人物访谈、圆桌对谈和用户故事。",
  category: "interview",
  recommendedFor: ["人物访谈", "问答对谈", "用户故事"],
  tokens: {
    colors: { background: "#ffffff", text: "#263238", muted: "#607d8b", accent: "#00796b", accentSoft: "#e0f2f1" },
    typography: { titleSize: 25, h2Size: 20, h3Size: 17, bodySize: 16, bodyLineHeight: 1.88 },
  },
  styles: {
    ...sharedStyles,
    titleWrap: "display:block;margin:0 0 25px;padding:0 0 15px;border-bottom:2px solid #00796b;",
    titleText: "display:block;color:#173f3a;font-size:25px;line-height:1.42;font-weight:800;",
    h2Wrap: "display:block;margin:34px 0 17px;padding:0;background:transparent;text-align:center;",
    h2Text: "display:inline-block;padding:6px 14px;border:1px solid #4db6ac;color:#00695c;font-size:20px;line-height:1.5;font-weight:750;",
    h3Wrap: "display:block;margin:25px 0 12px;padding:0 0 0 10px;border-left:3px solid #4db6ac;background:transparent;",
    h3Text: "display:block;color:#00695c;font-size:17px;line-height:1.55;font-weight:700;",
    paragraph: "display:block;margin:0 0 17px;padding:0;background:transparent;color:#263238;font-size:16px;line-height:1.88;text-align:justify;word-break:break-word;",
    dialogueWrap: "display:block;margin:22px 0;padding:16px;background:#f4fbfa;",
    dialogueSpeaker: "display:block;margin:0 0 6px;color:#00796b;font-size:14px;line-height:1.5;font-weight:800;",
    dialogueText: "display:block;margin:0 0 16px;padding:12px 14px;border-left:3px solid #80cbc4;background:#ffffff;color:#37474f;font-size:16px;line-height:1.8;",
    quoteWrap: "display:block;margin:24px 0;padding:20px;border-top:1px solid #80cbc4;border-bottom:1px solid #80cbc4;background:#ffffff;text-align:center;",
    quoteText: "display:block;margin:0;color:#174f48;font-size:18px;line-height:1.75;font-weight:700;",
    strong: "color:#00796b;font-weight:750;",
  },
};

const storyNarrative: WechatTheme = {
  id: "story-narrative",
  version: 1,
  name: "故事叙事",
  description: "弱化卡片、拉开章节节奏，适合个人经历、品牌故事和人物纪实。",
  category: "story",
  recommendedFor: ["个人故事", "人物纪实", "品牌叙事"],
  tokens: {
    colors: { background: "#fffefb", text: "#302f2c", muted: "#7c756b", accent: "#8b5e34", accentSoft: "#f7f1e8" },
    typography: { titleSize: 26, h2Size: 20, h3Size: 17, bodySize: 16, bodyLineHeight: 2 },
  },
  styles: {
    ...sharedStyles,
    root: "display:block;width:100%;box-sizing:border-box;padding:26px 18px;background:#fffefb;color:#302f2c;font-family:Georgia,'Songti SC','SimSun','Microsoft YaHei',serif;",
    titleWrap: "display:block;margin:0 0 30px;padding:0;text-align:center;",
    titleText: "display:block;color:#2f2b26;font-size:26px;line-height:1.48;font-weight:750;",
    subtitle: "display:block;margin:-16px 0 28px;color:#8a8175;font-size:14px;line-height:1.8;text-align:center;",
    h2Wrap: "display:block;margin:42px 0 20px;padding:0;background:transparent;text-align:center;",
    h2Text: "display:inline-block;padding:0 0 8px;border-bottom:1px solid #8b5e34;color:#4a3828;font-size:20px;line-height:1.55;font-weight:750;",
    h3Wrap: "display:block;margin:30px 0 14px;padding:0;background:transparent;",
    h3Text: "display:block;color:#6f4e37;font-size:17px;line-height:1.6;font-weight:700;",
    paragraph: "display:block;margin:0 0 20px;padding:0;background:transparent;color:#302f2c;font-size:16px;line-height:2;text-align:justify;word-break:break-word;",
    leadWrap: "display:block;margin:0 0 30px;padding:0 16px;border:0;background:transparent;",
    leadText: "display:block;margin:0;color:#665e55;font-size:16px;line-height:2;text-align:center;",
    quoteWrap: "display:block;margin:30px 0;padding:18px 20px;border:0;background:#f7f1e8;",
    quoteText: "display:block;margin:0;color:#5d4937;font-size:17px;line-height:1.9;font-style:italic;",
    divider: "display:block;width:24px;height:1px;margin:38px auto;border:0;background:#8b5e34;",
    strong: "color:#765332;font-weight:750;",
  },
};

const productIntroduction: WechatTheme = {
  id: "product-introduction",
  version: 1,
  name: "产品介绍",
  description: "按问题、方案、优势、适用人群和行动路径组织，适合服务与产品介绍。",
  category: "product",
  recommendedFor: ["产品介绍", "服务说明", "解决方案"],
  tokens: {
    colors: { background: "#ffffff", text: "#1f2937", muted: "#64748b", accent: "#2563eb", accentSoft: "#eff6ff" },
    typography: { titleSize: 25, h2Size: 20, h3Size: 17, bodySize: 16, bodyLineHeight: 1.84 },
  },
  styles: {
    ...sharedStyles,
    titleWrap: "display:block;margin:0 0 24px;padding:18px;border:1px solid #bfdbfe;background:#eff6ff;",
    titleText: "display:block;color:#172554;font-size:25px;line-height:1.42;font-weight:850;",
    h2Wrap: "display:block;margin:34px 0 16px;padding:9px 12px;border-left:5px solid #2563eb;background:#eff6ff;",
    h2Text: "display:block;color:#1e3a8a;font-size:20px;line-height:1.5;font-weight:800;",
    h3Wrap: "display:block;margin:25px 0 12px;padding:0;background:transparent;",
    h3Text: "display:block;color:#1d4ed8;font-size:17px;line-height:1.55;font-weight:750;",
    paragraph: "display:block;margin:0 0 16px;padding:0;background:transparent;color:#1f2937;font-size:16px;line-height:1.84;text-align:justify;word-break:break-word;",
    calloutWrap: "display:block;margin:20px 0;padding:16px;border:1px solid #bfdbfe;background:#f8fbff;",
    compareColumn: "display:table-cell;width:50%;padding:14px;border:1px solid #dbeafe;background:#ffffff;color:#334155;font-size:14px;line-height:1.75;vertical-align:top;",
    ctaWrap: "display:block;margin:30px 0 8px;padding:20px;border:0;background:#1d4ed8;text-align:center;",
    ctaTitle: "display:block;margin:0 0 8px;color:#ffffff;font-size:18px;line-height:1.5;font-weight:800;",
    ctaText: "display:block;margin:0;color:#eff6ff;font-size:15px;line-height:1.8;",
    strong: "color:#1d4ed8;font-weight:750;",
  },
};

const newsInformation: WechatTheme = {
  id: "news-information",
  version: 1,
  name: "新闻资讯",
  description: "突出时间、事件、背景和来源，适合热点解读、资讯快报与政策简报。",
  category: "news",
  recommendedFor: ["新闻资讯", "热点解读", "政策简报"],
  tokens: {
    colors: { background: "#ffffff", text: "#202124", muted: "#6b7280", accent: "#b42318", accentSoft: "#fef3f2" },
    typography: { titleSize: 26, h2Size: 20, h3Size: 17, bodySize: 16, bodyLineHeight: 1.82 },
  },
  styles: {
    ...sharedStyles,
    titleWrap: "display:block;margin:0 0 18px;padding:0 0 14px;border-bottom:1px solid #202124;",
    titleText: "display:block;color:#111827;font-family:Georgia,'Songti SC','SimSun',serif;font-size:26px;line-height:1.4;font-weight:800;",
    subtitle: "display:block;margin:-8px 0 24px;color:#6b7280;font-size:14px;line-height:1.7;",
    h2Wrap: "display:block;margin:34px 0 16px;padding:0 0 8px;border-bottom:2px solid #b42318;background:transparent;",
    h2Text: "display:block;color:#111827;font-size:20px;line-height:1.5;font-weight:800;",
    h3Wrap: "display:block;margin:25px 0 12px;padding:0 0 0 10px;border-left:3px solid #b42318;background:transparent;",
    h3Text: "display:block;color:#7f1d1d;font-size:17px;line-height:1.55;font-weight:700;",
    paragraph: "display:block;margin:0 0 16px;padding:0;background:transparent;color:#202124;font-size:16px;line-height:1.82;text-align:justify;word-break:break-word;",
    leadWrap: "display:block;margin:0 0 24px;padding:14px 16px;border-left:4px solid #b42318;background:#fef3f2;",
    leadText: "display:block;margin:0;color:#4b1f1b;font-size:16px;line-height:1.82;font-weight:600;",
    bylineWrap: "display:block;margin:28px 0 0;padding:14px 0;border-top:1px solid #d1d5db;background:transparent;",
    bylineAuthor: "display:block;margin:0 0 6px;color:#374151;font-size:14px;line-height:1.6;font-weight:700;",
    bylineText: "display:block;margin:0;color:#6b7280;font-size:13px;line-height:1.7;",
    quoteWrap: "display:block;margin:22px 0;padding:15px 17px;border-left:3px solid #9ca3af;background:#f9fafb;",
    strong: "color:#b42318;font-weight:750;",
  },
};

return {
  industryReport,
  interviewDialogue,
  storyNarrative,
  productIntroduction,
  newsInformation,
};
}
